apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: api
        image: 533267145447.dkr.ecr.us-east-1.amazonaws.com/private-repo:backend-v1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: connection_string
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        envFrom:
          - configMapRef:
              name: mongo-config
