apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: frontend
        image: 533267145447.dkr.ecr.us-east-1.amazonaws.com/private-repo:frontend-v1.0.0
        imagePullPolicy: ifNotPresent
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://dannythesec.online/api/tasks"
        ports:
        - containerPort: 3000
